export {
  type GraphNode,
  type GraphEdge,
  type IGraphStore,
  type VectorRecord,
  type VectorSearchRequest,
  type VectorSearchMatch,
  type IVectorIndex,
  type JobCheckpoint,
  type IMemoryStore,
} from './graphStore.js';
export {
  INDEXING_MEMORY_CONTRACT,
  type ActiveFactRequest,
  type ActivateFactsRequest,
  type IIndexingMemory,
  type IndexingMemoryDelta,
  type IndexingMemoryMutationPlan,
  type IndexingSchemaRequest,
} from './indexingMemory.js';
export {
  SCHEMA_CANONICALIZATION_CONTRACT,
  type GraphUpsertWireParams,
  type IndexingMemoryWireDelta,
  type LegacyGraphUpsertWireParams,
  type LegacyIndexingMemoryWireDelta,
  type SchemaCanonicalizationCapability,
  type SchemaCanonicalizationMemoryDelta,
  type SchemaCanonicalizationMergeCreate,
  type SchemaCanonicalizationMergeExisting,
  type SchemaCanonicalizationProjection,
  type SchemaCanonicalizationProjectionRequest,
  type SchemaHydrationWireParams,
  type SchemaMergeIntent,
  type SchemaNodeReference,
} from './schemaCanonicalization.js';
export {
  MEMORY_READ_CONTRACT,
  SNAPSHOT_MEMORY_READ_BOUNDS,
  type FactsByEntitiesRequest,
  type FactsByIdsRequest,
  type IMemoryReader,
  type MemoryFactStateFilter,
  type MemoryReadBounds,
  type MemorySectionCounts,
  type PassagesByIdsRequest,
  type SchemasByIdsRequest,
  type SectionCountsRequest,
} from './memoryReader.js';
