// Generated by scripts/generate-unicode16-lowercase.mjs. Do not edit.
import {
  UNICODE16_CASED_RANGES,
  UNICODE16_CASE_IGNORABLE_RANGES,
  UNICODE16_LOWERCASE_MAPPINGS,
} from './unicode16Lowercase.generated.js';

export const UNICODE16_LOWERCASE_DIGEST =
  'v15-entity-normalization-ecmascript-tolowercase-unicode16.0.0@1' as const;

const mappings = new Map<number, readonly number[]>(UNICODE16_LOWERCASE_MAPPINGS);

function inRanges(value: number, ranges: readonly (readonly [number, number])[]): boolean {
  let low = 0;
  let high = ranges.length - 1;
  while (low <= high) {
    const middle = (low + high) >>> 1;
    const [start, end] = ranges[middle]!;
    if (value < start) high = middle - 1;
    else if (value > end) low = middle + 1;
    else return true;
  }
  return false;
}

function scalarAt(value: string, index: number): number {
  const first = value.charCodeAt(index);
  if (first >= 0xD800 && first <= 0xDBFF) {
    const second = value.charCodeAt(index + 1);
    if (!(second >= 0xDC00 && second <= 0xDFFF)) {
      throw new TypeError('v15 entity normalization rejects an unpaired high surrogate');
    }
    return ((first - 0xD800) * 0x400) + (second - 0xDC00) + 0x10000;
  }
  if (first >= 0xDC00 && first <= 0xDFFF) {
    throw new TypeError('v15 entity normalization rejects an unpaired low surrogate');
  }
  return first;
}

function scalarWidth(value: string, index: number): number {
  const first = value.charCodeAt(index);
  if (first >= 0xD800 && first <= 0xDBFF) {
    const second = value.charCodeAt(index + 1);
    if (!(second >= 0xDC00 && second <= 0xDFFF)) {
      throw new TypeError('v15 entity normalization rejects an unpaired high surrogate');
    }
    return 2;
  }
  if (first >= 0xDC00 && first <= 0xDFFF) {
    throw new TypeError('v15 entity normalization rejects an unpaired low surrogate');
  }
  return 1;
}

function validateUtf16(value: string): void {
  for (let index = 0; index < value.length;) index += scalarWidth(value, index);
}

function previousScalarStart(value: string, index: number): number {
  let start = index - 1;
  const last = value.charCodeAt(start);
  if (last >= 0xDC00 && last <= 0xDFFF) start -= 1;
  return start;
}

function isFinalSigma(value: string, start: number, end: number): boolean {
  let before = previousScalarStart(value, start);
  while (before >= 0) {
    const scalar = scalarAt(value, before);
    if (!inRanges(scalar, UNICODE16_CASE_IGNORABLE_RANGES)) {
      if (!inRanges(scalar, UNICODE16_CASED_RANGES)) return false;
      break;
    }
    before = previousScalarStart(value, before);
  }
  if (before < 0) return false;
  let after = end;
  while (after < value.length) {
    const scalar = scalarAt(value, after);
    if (!inRanges(scalar, UNICODE16_CASE_IGNORABLE_RANGES)) {
      return !inRanges(scalar, UNICODE16_CASED_RANGES);
    }
    after += scalar > 0xFFFF ? 2 : 1;
  }
  return true;
}

/** Unicode 16.0.0 full lowercase for the v15 entity-comparison contract. */
export function unicode16Lowercase(value: string): string {
  validateUtf16(value);
  const chunks: string[] = [];
  const chunk = value.length > 4096 ? new Uint32Array(4096) : undefined;
  let chunkLength = 0;
  let smallOutput = '';
  const flush = (): void => {
    if (!chunk || chunkLength === 0) return;
    chunks.push(String.fromCodePoint(...chunk.subarray(0, chunkLength)));
    chunkLength = 0;
  };
  const append = (scalar: number): void => {
    if (!chunk) {
      smallOutput += String.fromCodePoint(scalar);
      return;
    }
    if (chunkLength === chunk.length) flush();
    chunk[chunkLength] = scalar;
    chunkLength += 1;
  };
  for (let index = 0; index < value.length;) {
    const start = index;
    const scalar = scalarAt(value, index);
    const next = index + (scalar > 0xFFFF ? 2 : 1);
    index = next;
    if (scalar === 0x03A3 && isFinalSigma(value, start, next)) {
      append(0x03C2);
      continue;
    }
    const mapping = mappings.get(scalar);
    if (mapping === undefined) {
      append(scalar);
      continue;
    }
    for (const mappedScalar of mapping) append(mappedScalar);
  }
  flush();
  return chunk ? chunks.join('') : smallOutput;
}
