// Generated by scripts/generate-unicode16-lowercase.mjs. Do not edit.
import {
  UNICODE16_CASED_RANGES,
  UNICODE16_CASE_IGNORABLE_RANGES,
  UNICODE16_LOWERCASE_MAPPINGS,
} from './unicode16Lowercase.generated.js';

export const UNICODE16_LOWERCASE_DIGEST =
  'v15-entity-normalization-ecmascript-tolowercase-unicode16.0.0@1' as const;

const mappings = new Map<number, readonly number[]>(UNICODE16_LOWERCASE_MAPPINGS);

function inRanges(value: number, ranges: readonly (readonly [number, number])[]): boolean {
  let low = 0;
  let high = ranges.length - 1;
  while (low <= high) {
    const middle = (low + high) >>> 1;
    const [start, end] = ranges[middle]!;
    if (value < start) high = middle - 1;
    else if (value > end) low = middle + 1;
    else return true;
  }
  return false;
}

function validatedScalars(value: string): number[] {
  const scalars: number[] = [];
  for (let index = 0; index < value.length; index += 1) {
    const first = value.charCodeAt(index);
    if (first >= 0xD800 && first <= 0xDBFF) {
      const second = value.charCodeAt(index + 1);
      if (!(second >= 0xDC00 && second <= 0xDFFF)) {
        throw new TypeError('v15 entity normalization rejects an unpaired high surrogate');
      }
      scalars.push(((first - 0xD800) * 0x400) + (second - 0xDC00) + 0x10000);
      index += 1;
      continue;
    }
    if (first >= 0xDC00 && first <= 0xDFFF) {
      throw new TypeError('v15 entity normalization rejects an unpaired low surrogate');
    }
    scalars.push(first);
  }
  return scalars;
}

function isFinalSigma(scalars: readonly number[], index: number): boolean {
  let before = index - 1;
  while (before >= 0 && inRanges(scalars[before]!, UNICODE16_CASE_IGNORABLE_RANGES)) before -= 1;
  if (before < 0 || !inRanges(scalars[before]!, UNICODE16_CASED_RANGES)) return false;
  let after = index + 1;
  while (after < scalars.length && inRanges(scalars[after]!, UNICODE16_CASE_IGNORABLE_RANGES)) after += 1;
  return after >= scalars.length || !inRanges(scalars[after]!, UNICODE16_CASED_RANGES);
}

/** Unicode 16.0.0 full lowercase for the v15 entity-comparison contract. */
export function unicode16Lowercase(value: string): string {
  const scalars = validatedScalars(value);
  const output: string[] = [];
  for (let index = 0; index < scalars.length; index += 1) {
    const scalar = scalars[index]!;
    if (scalar === 0x03A3 && isFinalSigma(scalars, index)) {
      output.push('ς');
      continue;
    }
    output.push(String.fromCodePoint(...(mappings.get(scalar) ?? [scalar])));
  }
  return output.join('');
}
